[package]
name = "keypairer"
version = "1.0.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
pqcrypto = "0.18.1"
pqcrypto-traits = "0.3.5"
zeroize = { version = "1.8.2", features = ["alloc"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
